### ISSUE TITLE
Build bot should ignore errors

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1630]
Lots of stuff we use has a habit of giving spurious errors e.g.

```
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]: Error: Validation took too long to complete; last status: {"guid":"tridactyl.vim.betas.nonewtab@cmcaine.co.uk","active":false,"automat>
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]:     at Timeout._onTimeout (/var/buildbot/tridactyl/node_modules/sign-addon/dist/webpack:/src/amo-client.js:232:16)
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]:     at listOnTimeout (internal/timers.js:535:17)
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]:     at processTimers (internal/timers.js:479:7)
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]: ls: write error: Broken pipe
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]: cp: 'web-ext-artifacts/nonewtab/tridactyl_no_new_tab_beta-latest.xpi' and 'web-ext-artifacts/nonewtab/tridactyl_no_new_tab_beta-latest>
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]: Build failed, resetting.
May 30 18:26:46 blanthornpc autobuild-tridactyl.sh[11748]: HEAD is now at 05f6fdc Fix #1600: try to massage bookmarks into proper URLs
May 30 18:26:46 blanthornpc systemd[782]: autobuild-tridactyl.service: Main process exited, code=exited, status=1/FAILURE

# build fails, resets, tries again in 5 minutes
```
...
```
May 30 18:27:20 blanthornpc autobuild-tridactyl.sh[13634]: Server response: Version already exists. Latest version is: 1.15.0pre2837. (status: 409)
May 30 18:27:20 blanthornpc autobuild-tridactyl.sh[13634]: FAIL
May 30 18:27:20 blanthornpc autobuild-tridactyl.sh[13634]: o: The extension could not be signed

# hammers server because of 409
```

We should also give up until there's a new commit on 409 errors.

**Comment by cmcaine** [comment]
It doesn't really hammer it: there's approximately one minute delay between attempts.
