### ISSUE TITLE
git post-checkout hook didn't work

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3086]
```
[I] ~/p/tridactyl (master|✔) $ hub checkout https://github.com/tridactyl/tridactyl/pull/3078


remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Total 13 (delta 10), reused 10 (delta 10), pack-reused 3
Unpacking objects: 100% (13/13), 1.58 KiB | 85.00 KiB/s, done.
From github.com:tridactyl/tridactyl
 * [new ref]           refs/pull/3078/head -> clipboard-api
Switched to branch 'clipboard-api'
Running post-checkout hook...
[I] ~/p/tridactyl (clipboard-api|✔) $ vim src/excmds.ts
[I] ~/p/tridactyl (clipboard-api|✚1) $ yarn run build && yarn run run
yarn run v1.22.10
$ sh scripts/build.sh

Using TypeScript 3.9.7 from /home/olie/projects/tridactyl/node_modules/typescript/lib
Rendering [========================================] 100%

Documentation generated at /home/olie/projects/tridactyl/generated/static/docs

Installing manifest here: /home/olie/.mozilla/native-messaging-hosts/
Installing script here: XDG_DATA_HOME: /home/olie/.local/share/tridactyl

Successfully installed Tridactyl native messenger!
Run ':native' in Firefox to check.

ERROR in ./src/lib/config.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /home/olie/projects/tridactyl/src/lib/config.ts.
    at makeSourceMapAndFinish (/home/olie/projects/tridactyl/node_modules/ts-loader/dist/index.js:53:18)
    at successLoader (/home/olie/projects/tridactyl/node_modules/ts-loader/dist/index.js:40:5)
    at Object.loader (/home/olie/projects/tridactyl/node_modules/ts-loader/dist/index.js:23:5)
 @ ./src/background.ts 12:0-42 31:4-10 110:4-19 129:0-15 157:4-19 164:0-24 222:11-24

ERROR in /home/olie/projects/tridactyl/src/lib/config.ts
./src/lib/config.ts
[tsl] ERROR in /home/olie/projects/tridactyl/src/lib/config.ts(22,29)
      TS2307: Cannot find module 'tsdef' or its corresponding type declarations.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[I] ~/p/tridactyl (clipboard-api|✚1) $ yarn install
```

it worked after the `yarn install`, so the post-checkout hook should have run `yarn install`. : /

**Comment by bovine3dom** [comment]
Probably PEBKAC.
